plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.78'
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    mavenCentral()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    runs {
        server {
            server()
            programArgument '--nogui'
        }
        client {
            client()
        }
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
            'Specification-Title'   : mod_id,
            'Specification-Vendor'  : mod_authors,
            'Specification-Version' : '1',
            'Implementation-Title'  : mod_name,
            'Implementation-Version': mod_version,
            'Implementation-Vendor' : mod_authors,
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}
